# scReportDE: Top navigation layout override ------------------------------------
#
# This file intentionally overrides build_html() from R/de_html.R.
# It keeps the existing section / widget builders unchanged, but renders the
# report navigation as a top horizontal tab bar instead of a left sidebar.

# ---- Top navigation CSS -------------------------------------------------------

top_nav_css <- function() {
'/* === scReportDE top navigation override === */

.report-body {
  flex: 1; min-height: 0;
  display: block;
  overflow: hidden;
}

.de-top-nav {
  flex-shrink: 0;
  background: #fff;
  border-right: none;
  border-bottom: 1px solid var(--sr-border);
  overflow-x: auto;
  overflow-y: hidden;
  padding: 0 24px;
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 6px;
  min-height: 44px;
  box-shadow: 0 1px 2px rgba(0,0,0,0.03);
}

.de-top-nav .de-nav-label {
  display: none;
}

.de-top-nav .de-nav-item {
  flex: 0 0 auto;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 34px;
  padding: 7px 14px;
  border-left: none;
  border-bottom: 3px solid transparent;
  border-radius: var(--sr-radius-sm) var(--sr-radius-sm) 0 0;
  font-size: 0.82em;
  font-weight: 500;
  white-space: nowrap;
}

.de-top-nav .de-nav-item:hover {
  background: var(--sr-accent-soft);
  color: var(--sr-text);
}

.de-top-nav .de-nav-item.active {
  background: var(--sr-accent-soft);
  border-left-color: transparent;
  border-bottom-color: var(--sr-accent);
  color: var(--sr-text);
  font-weight: 700;
}

.de-top-nav .de-nav-dot {
  display: none;
}

.de-content {
  height: 100%;
  padding: 20px 24px 40px;
}

@media (max-width: 800px) {
  .report-header {
    align-items: flex-start;
    flex-direction: column;
    gap: 4px;
  }

  .de-top-nav {
    display: flex;
    padding: 0 12px;
  }

  .de-top-nav .de-nav-item {
    padding: 7px 10px;
    font-size: 0.78em;
  }

  .de-content {
    padding: 16px 14px 36px;
  }
}
'
}


# ---- HTML Assembly: top nav version -----------------------------------------

build_html <- function(de_df, overview_cards, volcano_widget,
                       de_table_widget, dotplot_widget, violin_widget,
                       method_meta, generation_time,
                       output, title, self_contained, warnings) {

  # ---- Build sections ----

  sections <- list()

  sections$overview <- de_section(
    "overview", "Overview", visible = TRUE,
    warning_banner(warnings),
    htmltools::tags$div(class = "summary-cards", overview_cards)
  )

  sections$volcano <- de_section(
    "volcano", "Volcano Plot",
    if (!is.null(volcano_widget)) plot_block("Differential Expression Volcano", volcano_widget)
    else no_data_block("Volcano plot could not be generated. Check that de_df has logFC and p-value columns.")
  )

  sections$de_table <- de_section(
    "de_table", "DE Table",
    de_table_widget
  )

  if (!is.null(dotplot_widget)) {
    sections$dotplot <- dotplot_widget
  } else {
    sections$dotplot <- de_section(
      "dotplot", "Dot Plot",
      no_data_block("Dot plot requires a Seurat object and marker data for expression visualisation.")
    )
  }

  sections$violin <- de_section(
    "violin", "Violin Plot",
    if (!is.null(violin_widget)) plot_block("Top Gene Expression", violin_widget)
    else no_data_block("Violin plot requires a Seurat object for expression data.")
  )

  sections$method <- de_section(
    "method", "Method Info",
    build_method_info(method_meta, generation_time)
  )

  # ---- Build navigation ----
  nav_items <- list(
    htmltools::tags$div(class = "de-nav-label", "Report"),
    nav_item("overview", "Overview"),
    nav_item("volcano", "Volcano Plot"),
    nav_item("de_table", "DE Table"),
    nav_item("dotplot", "Dot Plot"),
    nav_item("violin", "Violin Plot"),
    nav_item("method", "Method Info")
  )

  # ---- Sharing notice ----
  if (!self_contained) {
    notice <- paste(
      "[!] This report is NOT self-contained.",
      "To share it with others, either:",
      "(1) send the HTML file together with the generated 'lib' folder, or",
      "(2) set self_contained = TRUE (not yet implemented in v0.1.0)."
    )
    warning_block <- htmltools::tags$div(
      class = "warning-banner",
      style = "margin:12px 0 0 0;",
      htmltools::tags$strong("\u26a0\ufe0f Sharing Notice:"),
      htmltools::tags$span(notice)
    )
    sections$overview <- htmltools::tagAppendChild(
      sections$overview, warning_block
    )
  }

  # ---- Build full page ----
  header <- htmltools::tags$header(class = "report-header",
    htmltools::tags$div(class = "report-title", title),
    htmltools::tags$div(class = "report-meta",
      "Differential Expression Report \u2014 scReportDE v0.1.0")
  )

  top_nav <- htmltools::tags$nav(class = "de-nav de-top-nav", nav_items)
  main    <- htmltools::tags$main(class = "de-content", sections)
  footer  <- htmltools::tags$footer(class = "report-footer",
    "Generated by scReportDE v0.1.0  |  scReport Ecosystem")

  script_tag <- htmltools::tags$script(
    htmltools::HTML(report_js())
  )

  page <- htmltools::tagList(
    htmltools::tags$head(
      htmltools::tags$meta(charset = "UTF-8"),
      htmltools::tags$meta(
        name = "viewport",
        content = "width=device-width, initial-scale=1.0"
      ),
      htmltools::tags$title(title),
      htmltools::tags$style(htmltools::HTML(report_css())),
      htmltools::tags$style(htmltools::HTML(top_nav_css()))
    ),
    htmltools::tags$body(
      htmltools::tags$div(class = "container",
        header,
        top_nav,
        htmltools::tags$div(class = "report-body",
          main
        ),
        footer
      ),
      script_tag
    )
  )

  htmltools::save_html(page, file = output)

  message("DE report written to: ", normalizePath(output, mustWork = FALSE))
  invisible(output)
}
